--도서 카테고리 테이블 생성 (성호)
CREATE TABLE M_BOOK_CATEGORY 
   (	BCATEGORYNO NUMBER, 
	BCATEGORY1 VARCHAR2(100 BYTE), 
	BCATEGORY2 VARCHAR2(100 BYTE)
   ) ;

Insert into M_BOOK_CATEGORY (BCATEGORYNO,BCATEGORY1,BCATEGORY2) values (1,'외국 도서','문학');
Insert into M_BOOK_CATEGORY (BCATEGORYNO,BCATEGORY1,BCATEGORY2) values (2,'국내 도서','소설');
Insert into M_BOOK_CATEGORY (BCATEGORYNO,BCATEGORY1,BCATEGORY2) values (3,'외국 도서','판타지');
Insert into M_BOOK_CATEGORY (BCATEGORYNO,BCATEGORY1,BCATEGORY2) values (4,'국내도설','판타지');
