CREATE TABLE M_COUPON 
   (	CPNO NUMBER, 
	CPNAME VARCHAR2(100), 
	CPDESCRIPTION VARCHAR2(225), 
	CPPRICE NUMBER, 
	CPCREATED DATE, 
	CPVALID DATE, 
	CPSTATUS VARCHAR2(10)
   );

INSERT INTO M_COUPON (CPNO,CPNAME,CPDESCRIPTION,CPPRICE,CPCREATED,CPVALID,CPSTATUS) 
    VALUES (1,'신규 가입 할인 쿠폰','신규가입 고객을 위한 할인 쿠폰',10000,to_date('23/09/07','RR/MM/DD'),to_date('23/09/14','RR/MM/DD'),'TRUE');
    
 
INSERT INTO M_COUPON (CPNO,CPNAME,CPDESCRIPTION,CPPRICE,CPCREATED,CPVALID,CPSTATUS) 
    VALUES(2,'WMBOOK 개업 이벤트','개업 이벤트',5000,to_date('23/09/07','RR/MM/DD'),to_date('23/09/14','RR/MM/DD'),'TRUE');    
    

INSERT INTO M_COUPON (CPNO,CPNAME,CPDESCRIPTION,CPPRICE,CPCREATED,CPVALID,CPSTATUS) 
    VALUES(3,'가을은 독서 이벤트','가을은 독서의 계절 책을 읽자',2000,to_date('23/09/07','RR/MM/DD'),to_date('23/11/15','RR/MM/DD'),'TRUE');  