  ---주문 상세 테이블 생성 (성호)
  CREATE TABLE M_ORDER_DETAIL 
   (	ORDERNO NUMBER, 
	BOOKNO NUMBER, 
	OPRICESELL NUMBER, 
	OCOUNT NUMBER, 
	OREFUND_CHECK VARCHAR2(50), 
	OREGDATE DATE
   ) ;

Insert into HR.M_ORDER_DETAIL (ORDERNO,BOOKNO,OPRICESELL,OCOUNT,OREFUND_CHECK,OREGDATE) values (12,12,12000,2,'가능',to_date('23/09/08','RR/MM/DD'));
Insert into HR.M_ORDER_DETAIL (ORDERNO,BOOKNO,OPRICESELL,OCOUNT,OREFUND_CHECK,OREGDATE) values (13,13,15000,2,'가능',to_date('23/09/05','RR/MM/DD'));
Insert into HR.M_ORDER_DETAIL (ORDERNO,BOOKNO,OPRICESELL,OCOUNT,OREFUND_CHECK,OREGDATE) values (11,16,17550,2,'가능',to_date('23/09/09','RR/MM/DD'));
Insert into HR.M_ORDER_DETAIL (ORDERNO,BOOKNO,OPRICESELL,OCOUNT,OREFUND_CHECK,OREGDATE) values (13,16,17550,2,'가능',to_date('23/09/05','RR/MM/DD'));
Insert into HR.M_ORDER_DETAIL (ORDERNO,BOOKNO,OPRICESELL,OCOUNT,OREFUND_CHECK,OREGDATE) values (13,14,18000,1,'가능',to_date('23/09/05','RR/MM/DD'));
Insert into HR.M_ORDER_DETAIL (ORDERNO,BOOKNO,OPRICESELL,OCOUNT,OREFUND_CHECK,OREGDATE) values (1,13,12000,2,'가능',to_date('23/08/23','RR/MM/DD'));
Insert into HR.M_ORDER_DETAIL (ORDERNO,BOOKNO,OPRICESELL,OCOUNT,OREFUND_CHECK,OREGDATE) values (2,13,15000,3,'가능',to_date('23/08/23','RR/MM/DD'));
Insert into HR.M_ORDER_DETAIL (ORDERNO,BOOKNO,OPRICESELL,OCOUNT,OREFUND_CHECK,OREGDATE) values (1,14,18000,1,'가능',to_date('23/08/23','RR/MM/DD'));
Insert into HR.M_ORDER_DETAIL (ORDERNO,BOOKNO,OPRICESELL,OCOUNT,OREFUND_CHECK,OREGDATE) values (3,14,18000,2,'가능',to_date('23/08/25','RR/MM/DD'));
Insert into HR.M_ORDER_DETAIL (ORDERNO,BOOKNO,OPRICESELL,OCOUNT,OREFUND_CHECK,OREGDATE) values (3,12,12000,1,'가능',to_date('23/08/13','RR/MM/DD'));
Insert into HR.M_ORDER_DETAIL (ORDERNO,BOOKNO,OPRICESELL,OCOUNT,OREFUND_CHECK,OREGDATE) values (4,15,15000,2,'가능',to_date('23/08/31','RR/MM/DD'));
Insert into HR.M_ORDER_DETAIL (ORDERNO,BOOKNO,OPRICESELL,OCOUNT,OREFUND_CHECK,OREGDATE) values (5,12,12000,2,'가능',to_date('23/09/01','RR/MM/DD'));
Insert into HR.M_ORDER_DETAIL (ORDERNO,BOOKNO,OPRICESELL,OCOUNT,OREFUND_CHECK,OREGDATE) values (6,13,12000,1,'가능',to_date('23/09/01','RR/MM/DD'));
Insert into HR.M_ORDER_DETAIL (ORDERNO,BOOKNO,OPRICESELL,OCOUNT,OREFUND_CHECK,OREGDATE) values (7,16,17550,2,'가능',to_date('23/09/08','RR/MM/DD'));
Insert into HR.M_ORDER_DETAIL (ORDERNO,BOOKNO,OPRICESELL,OCOUNT,OREFUND_CHECK,OREGDATE) values (8,13,15000,1,'가능',to_date('23/09/08','RR/MM/DD'));
Insert into HR.M_ORDER_DETAIL (ORDERNO,BOOKNO,OPRICESELL,OCOUNT,OREFUND_CHECK,OREGDATE) values (9,14,18000,1,'가능',to_date('23/09/08','RR/MM/DD'));
Insert into HR.M_ORDER_DETAIL (ORDERNO,BOOKNO,OPRICESELL,OCOUNT,OREFUND_CHECK,OREGDATE) values (10,15,15000,1,'가능',to_date('23/09/08','RR/MM/DD'));
Insert into HR.M_ORDER_DETAIL (ORDERNO,BOOKNO,OPRICESELL,OCOUNT,OREFUND_CHECK,OREGDATE) values (11,12,12000,1,'가능',to_date('23/09/09','RR/MM/DD'));