  CREATE TABLE M_ORDER (	
    ORDERNO NUMBER, 
	MEMBERNO NUMBER, 
	CPNO NUMBER, 
	OTOTALPRICE NUMBER, 
	OSTATUS VARCHAR2(50 BYTE), 
	OPAY VARCHAR2(20 BYTE)
   );

  Insert into HR.M_ORDER (ORDERNO,MEMBERNO,CPNO,OTOTALPRICE,OSTATUS,OPAY) values (1,1,1,42000,'배송완료','카드결제');
Insert into HR.M_ORDER (ORDERNO,MEMBERNO,CPNO,OTOTALPRICE,OSTATUS,OPAY) values (2,2,2,45000,'배송준비중','휴대폰 결제');
Insert into HR.M_ORDER (ORDERNO,MEMBERNO,CPNO,OTOTALPRICE,OSTATUS,OPAY) values (3,3,2,40000,'배송중','무통장 입금');