 CREATE TABLE M_ORDER_DETAIL (	
    ORDERNO NUMBER, 
	BOOKNO NUMBER, 
	OPRICESELL NUMBER, 
	OCOUNT NUMBER, 
	OREFUND_CHECK VARCHAR2(50), 
	OREGDATE DATE
   );

Insert into M_ORDER_DETAIL (ORDERNO,BOOKNO,OPRICESELL,OCOUNT,OREFUND_CHECK,OREGDATE) values (1,13,12000,2,'가능',to_date('23/08/23','RR/MM/DD'));
Insert into M_ORDER_DETAIL (ORDERNO,BOOKNO,OPRICESELL,OCOUNT,OREFUND_CHECK,OREGDATE) values (2,13,15000,3,'가능',to_date('23/08/23','RR/MM/DD'));
Insert into M_ORDER_DETAIL (ORDERNO,BOOKNO,OPRICESELL,OCOUNT,OREFUND_CHECK,OREGDATE) values (1,14,18000,1,'가능',to_date('23/08/23','RR/MM/DD'));
Insert into M_ORDER_DETAIL (ORDERNO,BOOKNO,OPRICESELL,OCOUNT,OREFUND_CHECK,OREGDATE) values (3,14,18000,2,'가능',to_date('23/08/25','RR/MM/DD'));
Insert into M_ORDER_DETAIL (ORDERNO,BOOKNO,OPRICESELL,OCOUNT,OREFUND_CHECK,OREGDATE) values (3,12,12000,1,'가능',to_date('23/08/13','RR/MM/DD'));