--주문 테이블 생성 (성호)

  CREATE TABLE M_ORDER 
   (	ORDERNO NUMBER, 
	MEMBERNO NUMBER, 
	CPNO NUMBER, 
	OTOTALPRICE NUMBER, 
	OSTATUS VARCHAR2(50 BYTE), 
	OPAY VARCHAR2(20 BYTE)
   );

Insert into HR.M_ORDER (ORDERNO,MEMBERNO,CPNO,OTOTALPRICE,OSTATUS,OPAY) values (1,1,1,42000,'배송완료','카드결제');
Insert into HR.M_ORDER (ORDERNO,MEMBERNO,CPNO,OTOTALPRICE,OSTATUS,OPAY) values (2,2,2,45000,'배송중','휴대폰 결제');
Insert into HR.M_ORDER (ORDERNO,MEMBERNO,CPNO,OTOTALPRICE,OSTATUS,OPAY) values (11,3,1,47100,'배송준비중','휴대폰 결제');
Insert into HR.M_ORDER (ORDERNO,MEMBERNO,CPNO,OTOTALPRICE,OSTATUS,OPAY) values (13,5,1,80100,'배송준비중','카드결제');
Insert into HR.M_ORDER (ORDERNO,MEMBERNO,CPNO,OTOTALPRICE,OSTATUS,OPAY) values (3,3,2,40000,'배송중','무통장 입금');
Insert into HR.M_ORDER (ORDERNO,MEMBERNO,CPNO,OTOTALPRICE,OSTATUS,OPAY) values (4,1,2,30000,'배송준비중','카드결제');
Insert into HR.M_ORDER (ORDERNO,MEMBERNO,CPNO,OTOTALPRICE,OSTATUS,OPAY) values (5,1,1,24000,'배송준비중','카드결제');
Insert into HR.M_ORDER (ORDERNO,MEMBERNO,CPNO,OTOTALPRICE,OSTATUS,OPAY) values (6,1,1,15000,'배송준비중','카드결제');
Insert into HR.M_ORDER (ORDERNO,MEMBERNO,CPNO,OTOTALPRICE,OSTATUS,OPAY) values (7,5,1,17550,'배송준비중','카드결제');
Insert into HR.M_ORDER (ORDERNO,MEMBERNO,CPNO,OTOTALPRICE,OSTATUS,OPAY) values (8,6,1,15000,'배송준비중','휴대폰 결제');
Insert into HR.M_ORDER (ORDERNO,MEMBERNO,CPNO,OTOTALPRICE,OSTATUS,OPAY) values (9,6,1,18000,'배송준비중','휴대폰 결제');
Insert into HR.M_ORDER (ORDERNO,MEMBERNO,CPNO,OTOTALPRICE,OSTATUS,OPAY) values (10,3,2,15000,'배송준비중','카드결제');
Insert into HR.M_ORDER (ORDERNO,MEMBERNO,CPNO,OTOTALPRICE,OSTATUS,OPAY) values (12,2,2,12000,'배송준비중','카드결제');